FROM openjdk:8-jdk-alpine

RUN mkdir /app

COPY ./build/libs/TreeHollowBE-0.0.1-SNAPSHOT.jar /app/server.jar

WORKDIR /app

RUN apk add --no-cache fontconfig ttf-dejavu

ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

CMD ["java", "-jar", "server.jar"]

EXPOSE 5000

